"""initial

Revision ID: 3c1548be7b9e
Revises: 
Create Date: 2026-05-12 22:50:36.891476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c1548be7b9e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('wheel_type', sa.String(length=20), nullable=False),
    sa.Column('bankroll_init', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('bet_unit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('bankroll_now', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('excluded_dozens', sa.JSON(), nullable=False),
    sa.Column('initial_history', sa.JSON(), nullable=False),
    sa.Column('external_stats', sa.JSON(), nullable=True),
    sa.Column('external_stats_n_estimate', sa.Integer(), nullable=True),
    sa.Column('hyperparams', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reflection',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('at_spin_index', sa.Integer(), nullable=True),
    sa.Column('observation', sa.Text(), nullable=True),
    sa.Column('hyperparam_diff', sa.JSON(), nullable=True),
    sa.Column('notes_diff', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reflection', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reflection_session_id'), ['session_id'], unique=False)

    op.create_table('spin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('spin_index', sa.Integer(), nullable=False),
    sa.Column('bets', sa.JSON(), nullable=True),
    sa.Column('bets_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('result_number', sa.Integer(), nullable=False),
    sa.Column('pnl', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('bankroll_after', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('bias_report', sa.JSON(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spin', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spin_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spin_session_id'))

    op.drop_table('spin')
    with op.batch_alter_table('reflection', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reflection_session_id'))

    op.drop_table('reflection')
    op.drop_table('session')
    # ### end Alembic commands ###
